remote_theme: "mmistakes/minimal-mistakes@4.26.2"
url: https://urskr.github.io
baseurl: /recipes
title: Meine Rezepte
description: "Stuff I like to cook."
repository: "urskr/recipes"

include: ["_pages"]

locale: de-DE
search: true
lunr:
  search_within_pages: true

defaults:
  # _posts
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Urs"
      author_profile: true
      toc: true
      toc_label: Inhalt
      toc_sticky: true
      show_date: true
      tagline: "" #else posts show their first line as tagline
      #header:
        #overlay_image: /assets/images/image.png

plugins:
  - jekyll-feed
  - jekyll-include-cache

exclude:
   - alte_rezepte/

paginate: 10
paginate_path: /page:num/