theme: jekyll-theme-architect
url: https://urskr.github.io
baseurl: /recipes
title: Meine Rezepte
collections:
  labels:
    output: true
    permalink: /tags/:path/
  types:
    output: true
    permalink: /types/:path/
  sides:
    output: true
    permalink: /sides/:path/
  meats:
    output: true
    permalink: /meats/:path/
  origins:
    output: true
    permalink: /origins/:path/
